Add complete Game
MarcRaeder/Zahlenraten pull request #1
Opened 2022-10-18 11:55 UTC by MarcRaeder

Add complete Game

2022-10-19 12:35 UTC, DevBastiS requested changes

2022-10-19 12:35 UTC, DevBastiS commented on zahlenRaten.py
> +    max = 100
Können als Konstanten oben in der Datei deklariert werden und einen sprechenderen Namen bekommen.

2022-10-19 12:35 UTC, DevBastiS commented on zahlenRaten.py
> +
```suggestion
```

2022-10-19 12:35 UTC, DevBastiS commented on zahlenRaten.py
> +    trys = 0
```suggestion
    tries = 0
```

oder "versuche" oder "attempts"

2022-10-19 14:09 UTC, stefanluth requested changes

2022-10-19 14:09 UTC, stefanluth commented on zahlenRaten.py
> +                break
Calling `game()` inside `game()` will cause nested function. This means when you play 20 rounds in a row, you will have 20 running games, all stuck at line 71 and then quitting would quit all 20 games at once. It's preferable to only have one instance of the game at any given time.

2022-10-24 08:01 UTC, stefanluth commented on zahlenRaten.py
> +                      tries, "Versuche gebraucht.\nMöchtest du nochmal spielen? Dann gebe 'JA' ein.\nFalls nicht dann gib irgendwas anderes ein.")
```suggestion
                print("Das war richtig. Nice! Du hast",
                    tries, "Versuche gebraucht.\nMöchtest du nochmal spielen? Dann gebe 'JA' ein.\nFalls nicht dann gib irgendwas anderes ein.")
```
Indentation is off and the line is kinda long :)

2022-10-24 08:03 UTC, stefanluth commented on zahlenRaten.py
> +    print("Auf Wiedersehen")
The game will only be playable one more time, instead of having an endless loop

2022-10-24 08:09 UTC, stefanluth approved these changes

2022-10-25 06:20 UTC, DevBastiS approved these changes

2022-10-25 06:21 UTC, merged